# Generated by Django 5.2 on 2026-04-14 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_userstat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstat',
            name='avatar_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
